-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Object exposing (AggregateAsset(..), AggregateCallToAction(..), AggregateColor(..), AggregateExplanationBlock(..), AggregateFaq(..), AggregateLocation(..), AggregatePage(..), Asset(..), AssetConnection(..), AssetEdge(..), AssetPreviousValues(..), AssetSubscriptionPayload(..), BatchPayload(..), CallToAction(..), CallToActionConnection(..), CallToActionEdge(..), CallToActionPreviousValues(..), CallToActionSubscriptionPayload(..), Color(..), ColorConnection(..), ColorEdge(..), ColorPreviousValues(..), ColorSubscriptionPayload(..), ExplanationBlock(..), ExplanationBlockConnection(..), ExplanationBlockEdge(..), ExplanationBlockPreviousValues(..), ExplanationBlockSubscriptionPayload(..), Faq(..), FaqConnection(..), FaqEdge(..), FaqPreviousValues(..), FaqSubscriptionPayload(..), Location(..), LocationConnection(..), LocationEdge(..), LocationPreviousValues(..), LocationSubscriptionPayload(..), Page(..), PageConnection(..), PageEdge(..), PageInfo(..), PagePreviousValues(..), PageSubscriptionPayload(..))


type AggregateAsset
    = AggregateAsset


type AggregateCallToAction
    = AggregateCallToAction


type AggregateColor
    = AggregateColor


type AggregateExplanationBlock
    = AggregateExplanationBlock


type AggregateFaq
    = AggregateFaq


type AggregateLocation
    = AggregateLocation


type AggregatePage
    = AggregatePage


type Asset
    = Asset


type AssetConnection
    = AssetConnection


type AssetEdge
    = AssetEdge


type AssetPreviousValues
    = AssetPreviousValues


type AssetSubscriptionPayload
    = AssetSubscriptionPayload


type BatchPayload
    = BatchPayload


type CallToAction
    = CallToAction


type CallToActionConnection
    = CallToActionConnection


type CallToActionEdge
    = CallToActionEdge


type CallToActionPreviousValues
    = CallToActionPreviousValues


type CallToActionSubscriptionPayload
    = CallToActionSubscriptionPayload


type Color
    = Color


type ColorConnection
    = ColorConnection


type ColorEdge
    = ColorEdge


type ColorPreviousValues
    = ColorPreviousValues


type ColorSubscriptionPayload
    = ColorSubscriptionPayload


type ExplanationBlock
    = ExplanationBlock


type ExplanationBlockConnection
    = ExplanationBlockConnection


type ExplanationBlockEdge
    = ExplanationBlockEdge


type ExplanationBlockPreviousValues
    = ExplanationBlockPreviousValues


type ExplanationBlockSubscriptionPayload
    = ExplanationBlockSubscriptionPayload


type Faq
    = Faq


type FaqConnection
    = FaqConnection


type FaqEdge
    = FaqEdge


type FaqPreviousValues
    = FaqPreviousValues


type FaqSubscriptionPayload
    = FaqSubscriptionPayload


type Location
    = Location


type LocationConnection
    = LocationConnection


type LocationEdge
    = LocationEdge


type LocationPreviousValues
    = LocationPreviousValues


type LocationSubscriptionPayload
    = LocationSubscriptionPayload


type Page
    = Page


type PageConnection
    = PageConnection


type PageEdge
    = PageEdge


type PageInfo
    = PageInfo


type PagePreviousValues
    = PagePreviousValues


type PageSubscriptionPayload
    = PageSubscriptionPayload
