-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Scalar exposing (DateTime(..), Id(..), Long(..))


type DateTime
    = DateTime String


type Id
    = Id String


type Long
    = Long String
