-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Object.AssetPreviousValues exposing (createdAt, fileName, handle, height, id, mimeType, size, status, updatedAt, width)

import CMS.Enum.Status
import CMS.InputObject
import CMS.Interface
import CMS.Object
import CMS.Scalar
import CMS.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet CMS.Enum.Status.Status CMS.Object.AssetPreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] CMS.Enum.Status.decoder


id : SelectionSet CMS.Scalar.Id CMS.Object.AssetPreviousValues
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.Id)


createdAt : SelectionSet CMS.Scalar.DateTime CMS.Object.AssetPreviousValues
createdAt =
    Object.selectionForField "Scalar.DateTime" "createdAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


updatedAt : SelectionSet CMS.Scalar.DateTime CMS.Object.AssetPreviousValues
updatedAt =
    Object.selectionForField "Scalar.DateTime" "updatedAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


handle : SelectionSet String CMS.Object.AssetPreviousValues
handle =
    Object.selectionForField "String" "handle" [] Decode.string


fileName : SelectionSet String CMS.Object.AssetPreviousValues
fileName =
    Object.selectionForField "String" "fileName" [] Decode.string


height : SelectionSet (Maybe Float) CMS.Object.AssetPreviousValues
height =
    Object.selectionForField "(Maybe Float)" "height" [] (Decode.float |> Decode.nullable)


mimeType : SelectionSet (Maybe String) CMS.Object.AssetPreviousValues
mimeType =
    Object.selectionForField "(Maybe String)" "mimeType" [] (Decode.string |> Decode.nullable)


size : SelectionSet (Maybe Float) CMS.Object.AssetPreviousValues
size =
    Object.selectionForField "(Maybe Float)" "size" [] (Decode.float |> Decode.nullable)


width : SelectionSet (Maybe Float) CMS.Object.AssetPreviousValues
width =
    Object.selectionForField "(Maybe Float)" "width" [] (Decode.float |> Decode.nullable)
