-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Object.CallToActionPreviousValues exposing (actionUrl, createdAt, id, label, placement, status, updatedAt)

import CMS.Enum.CallToActionPlacement
import CMS.Enum.Status
import CMS.InputObject
import CMS.Interface
import CMS.Object
import CMS.Scalar
import CMS.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet CMS.Enum.Status.Status CMS.Object.CallToActionPreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] CMS.Enum.Status.decoder


id : SelectionSet CMS.Scalar.Id CMS.Object.CallToActionPreviousValues
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.Id)


createdAt : SelectionSet CMS.Scalar.DateTime CMS.Object.CallToActionPreviousValues
createdAt =
    Object.selectionForField "Scalar.DateTime" "createdAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


updatedAt : SelectionSet CMS.Scalar.DateTime CMS.Object.CallToActionPreviousValues
updatedAt =
    Object.selectionForField "Scalar.DateTime" "updatedAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


placement : SelectionSet (Maybe CMS.Enum.CallToActionPlacement.CallToActionPlacement) CMS.Object.CallToActionPreviousValues
placement =
    Object.selectionForField "(Maybe Enum.CallToActionPlacement.CallToActionPlacement)" "placement" [] (CMS.Enum.CallToActionPlacement.decoder |> Decode.nullable)


actionUrl : SelectionSet (Maybe String) CMS.Object.CallToActionPreviousValues
actionUrl =
    Object.selectionForField "(Maybe String)" "actionUrl" [] (Decode.string |> Decode.nullable)


label : SelectionSet (Maybe String) CMS.Object.CallToActionPreviousValues
label =
    Object.selectionForField "(Maybe String)" "label" [] (Decode.string |> Decode.nullable)
