-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Object.ExplanationBlockPreviousValues exposing (createdAt, icon, id, status, text, title, type_, updatedAt)

import CMS.Enum.ExplanationTypes
import CMS.Enum.Status
import CMS.InputObject
import CMS.Interface
import CMS.Object
import CMS.Scalar
import CMS.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet CMS.Enum.Status.Status CMS.Object.ExplanationBlockPreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] CMS.Enum.Status.decoder


id : SelectionSet CMS.Scalar.Id CMS.Object.ExplanationBlockPreviousValues
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.Id)


createdAt : SelectionSet CMS.Scalar.DateTime CMS.Object.ExplanationBlockPreviousValues
createdAt =
    Object.selectionForField "Scalar.DateTime" "createdAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


updatedAt : SelectionSet CMS.Scalar.DateTime CMS.Object.ExplanationBlockPreviousValues
updatedAt =
    Object.selectionForField "Scalar.DateTime" "updatedAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


title : SelectionSet (Maybe String) CMS.Object.ExplanationBlockPreviousValues
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


text : SelectionSet (Maybe String) CMS.Object.ExplanationBlockPreviousValues
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)


type_ : SelectionSet CMS.Enum.ExplanationTypes.ExplanationTypes CMS.Object.ExplanationBlockPreviousValues
type_ =
    Object.selectionForField "Enum.ExplanationTypes.ExplanationTypes" "type" [] CMS.Enum.ExplanationTypes.decoder


icon : SelectionSet (Maybe String) CMS.Object.ExplanationBlockPreviousValues
icon =
    Object.selectionForField "(Maybe String)" "icon" [] (Decode.string |> Decode.nullable)
