-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Object.PagePreviousValues exposing (createdAt, heading, id, path, status, subtitle, title, updatedAt)

import CMS.Enum.Status
import CMS.InputObject
import CMS.Interface
import CMS.Object
import CMS.Scalar
import CMS.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


status : SelectionSet CMS.Enum.Status.Status CMS.Object.PagePreviousValues
status =
    Object.selectionForField "Enum.Status.Status" "status" [] CMS.Enum.Status.decoder


id : SelectionSet CMS.Scalar.Id CMS.Object.PagePreviousValues
id =
    Object.selectionForField "Scalar.Id" "id" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.Id)


createdAt : SelectionSet CMS.Scalar.DateTime CMS.Object.PagePreviousValues
createdAt =
    Object.selectionForField "Scalar.DateTime" "createdAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


updatedAt : SelectionSet CMS.Scalar.DateTime CMS.Object.PagePreviousValues
updatedAt =
    Object.selectionForField "Scalar.DateTime" "updatedAt" [] (Object.scalarDecoder |> Decode.map CMS.Scalar.DateTime)


title : SelectionSet (Maybe String) CMS.Object.PagePreviousValues
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


heading : SelectionSet (Maybe String) CMS.Object.PagePreviousValues
heading =
    Object.selectionForField "(Maybe String)" "heading" [] (Decode.string |> Decode.nullable)


subtitle : SelectionSet (Maybe String) CMS.Object.PagePreviousValues
subtitle =
    Object.selectionForField "(Maybe String)" "subtitle" [] (Decode.string |> Decode.nullable)


path : SelectionSet String CMS.Object.PagePreviousValues
path =
    Object.selectionForField "String" "path" [] Decode.string
