-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.ContributionsCollection exposing (FirstIssueContributionOptionalArguments, FirstPullRequestContributionOptionalArguments, JoinedGitHubContributionOptionalArguments, TotalIssueContributionsOptionalArguments, TotalPullRequestContributionsOptionalArguments, TotalRepositoriesWithContributedIssuesOptionalArguments, TotalRepositoriesWithContributedPullRequestsOptionalArguments, TotalRepositoryContributionsOptionalArguments, contributionCalendar, doesEndInCurrentMonth, earliestRestrictedContributionDate, endedAt, firstIssueContribution, firstPullRequestContribution, hasActivityInThePast, hasAnyContributions, hasAnyRestrictedContributions, isSingleDay, joinedGitHubContribution, latestRestrictedContributionDate, mostRecentCollectionWithActivity, mostRecentCollectionWithoutActivity, popularIssueContribution, popularPullRequestContribution, restrictedContributionsCount, startedAt, totalCommitContributions, totalIssueContributions, totalPullRequestContributions, totalPullRequestReviewContributions, totalRepositoriesWithContributedCommits, totalRepositoriesWithContributedIssues, totalRepositoriesWithContributedPullRequestReviews, totalRepositoriesWithContributedPullRequests, totalRepositoryContributions, user)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A calendar of this user's contributions on GitHub.
-}
contributionCalendar : SelectionSet decodesTo Github.Object.ContributionCalendar -> SelectionSet decodesTo Github.Object.ContributionsCollection
contributionCalendar object_ =
    Object.selectionForCompositeField "contributionCalendar" [] object_ identity


{-| Determine if this collection's time span ends in the current month.
-}
doesEndInCurrentMonth : SelectionSet Bool Github.Object.ContributionsCollection
doesEndInCurrentMonth =
    Object.selectionForField "Bool" "doesEndInCurrentMonth" [] Decode.bool


{-| The date of the first restricted contribution the user made in this time period. Can only be non-null when the user has enabled private contribution counts.
-}
earliestRestrictedContributionDate : SelectionSet (Maybe Github.Scalar.Date) Github.Object.ContributionsCollection
earliestRestrictedContributionDate =
    Object.selectionForField "(Maybe Scalar.Date)" "earliestRestrictedContributionDate" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Date |> Decode.nullable)


{-| The ending date and time of this collection.
-}
endedAt : SelectionSet Github.Scalar.DateTime Github.Object.ContributionsCollection
endedAt =
    Object.selectionForField "Scalar.DateTime" "endedAt" [] (Object.scalarDecoder |> Decode.map Github.Scalar.DateTime)


type alias FirstIssueContributionOptionalArguments =
    { ignoreTimeRange : OptionalArgument Bool }


{-| The first issue the user opened on GitHub. This will be null if that issue was opened outside the collection's time range and ignoreTimeRange is false. If the issue is not visible but the user has opted to show private contributions, a RestrictedContribution will be returned.

  - ignoreTimeRange - If true, the first issue will be returned even if it was opened outside of the collection's time range.

-}
firstIssueContribution : (FirstIssueContributionOptionalArguments -> FirstIssueContributionOptionalArguments) -> SelectionSet decodesTo Github.Union.CreatedIssueOrRestrictedContribution -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
firstIssueContribution fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { ignoreTimeRange = Absent }

        optionalArgs =
            [ Argument.optional "ignoreTimeRange" filledInOptionals.ignoreTimeRange Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "firstIssueContribution" optionalArgs object_ (identity >> Decode.nullable)


type alias FirstPullRequestContributionOptionalArguments =
    { ignoreTimeRange : OptionalArgument Bool }


{-| The first pull request the user opened on GitHub. This will be null if that pull request was opened outside the collection's time range and ignoreTimeRange is not true. If the pull request is not visible but the user has opted to show private contributions, a RestrictedContribution will be returned.

  - ignoreTimeRange - If true, the first pull request will be returned even if it was opened outside of the collection's time range.

-}
firstPullRequestContribution : (FirstPullRequestContributionOptionalArguments -> FirstPullRequestContributionOptionalArguments) -> SelectionSet decodesTo Github.Union.CreatedPullRequestOrRestrictedContribution -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
firstPullRequestContribution fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { ignoreTimeRange = Absent }

        optionalArgs =
            [ Argument.optional "ignoreTimeRange" filledInOptionals.ignoreTimeRange Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "firstPullRequestContribution" optionalArgs object_ (identity >> Decode.nullable)


{-| Does the user have any more activity in the timeline that occurred prior to the collection's time range?
-}
hasActivityInThePast : SelectionSet Bool Github.Object.ContributionsCollection
hasActivityInThePast =
    Object.selectionForField "Bool" "hasActivityInThePast" [] Decode.bool


{-| Determine if there are any contributions in this collection.
-}
hasAnyContributions : SelectionSet Bool Github.Object.ContributionsCollection
hasAnyContributions =
    Object.selectionForField "Bool" "hasAnyContributions" [] Decode.bool


{-| Determine if the user made any contributions in this time frame whose details are not visible because they were made in a private repository. Can only be true if the user enabled private contribution counts.
-}
hasAnyRestrictedContributions : SelectionSet Bool Github.Object.ContributionsCollection
hasAnyRestrictedContributions =
    Object.selectionForField "Bool" "hasAnyRestrictedContributions" [] Decode.bool


{-| Whether or not the collector's time span is all within the same day.
-}
isSingleDay : SelectionSet Bool Github.Object.ContributionsCollection
isSingleDay =
    Object.selectionForField "Bool" "isSingleDay" [] Decode.bool


type alias JoinedGitHubContributionOptionalArguments =
    { ignoreTimeRange : OptionalArgument Bool }


{-| When the user signed up for GitHub. This will be null if that sign up date falls outside the collection's time range and ignoreTimeRange is false.

  - ignoreTimeRange - If true, the contribution will be returned even if the user signed up outside of the collection's time range.

-}
joinedGitHubContribution : (JoinedGitHubContributionOptionalArguments -> JoinedGitHubContributionOptionalArguments) -> SelectionSet decodesTo Github.Object.JoinedGitHubContribution -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
joinedGitHubContribution fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { ignoreTimeRange = Absent }

        optionalArgs =
            [ Argument.optional "ignoreTimeRange" filledInOptionals.ignoreTimeRange Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "joinedGitHubContribution" optionalArgs object_ (identity >> Decode.nullable)


{-| The date of the most recent restricted contribution the user made in this time period. Can only be non-null when the user has enabled private contribution counts.
-}
latestRestrictedContributionDate : SelectionSet (Maybe Github.Scalar.Date) Github.Object.ContributionsCollection
latestRestrictedContributionDate =
    Object.selectionForField "(Maybe Scalar.Date)" "latestRestrictedContributionDate" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Date |> Decode.nullable)


{-| When this collection's time range does not include any activity from the user, use this
to get a different collection from an earlier time range that does have activity.
-}
mostRecentCollectionWithActivity : SelectionSet decodesTo Github.Object.ContributionsCollection -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
mostRecentCollectionWithActivity object_ =
    Object.selectionForCompositeField "mostRecentCollectionWithActivity" [] object_ (identity >> Decode.nullable)


{-| Returns a different contributions collection from an earlier time range than this one
that does not have any contributions.
-}
mostRecentCollectionWithoutActivity : SelectionSet decodesTo Github.Object.ContributionsCollection -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
mostRecentCollectionWithoutActivity object_ =
    Object.selectionForCompositeField "mostRecentCollectionWithoutActivity" [] object_ (identity >> Decode.nullable)


{-| The issue the user opened on GitHub that received the most comments in the specified
time frame.
-}
popularIssueContribution : SelectionSet decodesTo Github.Object.CreatedIssueContribution -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
popularIssueContribution object_ =
    Object.selectionForCompositeField "popularIssueContribution" [] object_ (identity >> Decode.nullable)


{-| The pull request the user opened on GitHub that received the most comments in the
specified time frame.
-}
popularPullRequestContribution : SelectionSet decodesTo Github.Object.CreatedPullRequestContribution -> SelectionSet (Maybe decodesTo) Github.Object.ContributionsCollection
popularPullRequestContribution object_ =
    Object.selectionForCompositeField "popularPullRequestContribution" [] object_ (identity >> Decode.nullable)


{-| A count of contributions made by the user that the viewer cannot access. Only non-zero when the user has chosen to share their private contribution counts.
-}
restrictedContributionsCount : SelectionSet Int Github.Object.ContributionsCollection
restrictedContributionsCount =
    Object.selectionForField "Int" "restrictedContributionsCount" [] Decode.int


{-| The beginning date and time of this collection.
-}
startedAt : SelectionSet Github.Scalar.DateTime Github.Object.ContributionsCollection
startedAt =
    Object.selectionForField "Scalar.DateTime" "startedAt" [] (Object.scalarDecoder |> Decode.map Github.Scalar.DateTime)


{-| How many commits were made by the user in this time span.
-}
totalCommitContributions : SelectionSet Int Github.Object.ContributionsCollection
totalCommitContributions =
    Object.selectionForField "Int" "totalCommitContributions" [] Decode.int


type alias TotalIssueContributionsOptionalArguments =
    { excludeFirst : OptionalArgument Bool
    , excludePopular : OptionalArgument Bool
    }


{-| How many issues the user opened.

  - excludeFirst - Should the user's first issue ever be excluded from this count.
  - excludePopular - Should the user's most commented issue be excluded from this count.

-}
totalIssueContributions : (TotalIssueContributionsOptionalArguments -> TotalIssueContributionsOptionalArguments) -> SelectionSet Int Github.Object.ContributionsCollection
totalIssueContributions fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { excludeFirst = Absent, excludePopular = Absent }

        optionalArgs =
            [ Argument.optional "excludeFirst" filledInOptionals.excludeFirst Encode.bool, Argument.optional "excludePopular" filledInOptionals.excludePopular Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForField "Int" "totalIssueContributions" optionalArgs Decode.int


type alias TotalPullRequestContributionsOptionalArguments =
    { excludeFirst : OptionalArgument Bool
    , excludePopular : OptionalArgument Bool
    }


{-| How many pull requests the user opened.

  - excludeFirst - Should the user's first pull request ever be excluded from this count.
  - excludePopular - Should the user's most commented pull request be excluded from this count.

-}
totalPullRequestContributions : (TotalPullRequestContributionsOptionalArguments -> TotalPullRequestContributionsOptionalArguments) -> SelectionSet Int Github.Object.ContributionsCollection
totalPullRequestContributions fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { excludeFirst = Absent, excludePopular = Absent }

        optionalArgs =
            [ Argument.optional "excludeFirst" filledInOptionals.excludeFirst Encode.bool, Argument.optional "excludePopular" filledInOptionals.excludePopular Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForField "Int" "totalPullRequestContributions" optionalArgs Decode.int


{-| How many pull request reviews the user left.
-}
totalPullRequestReviewContributions : SelectionSet Int Github.Object.ContributionsCollection
totalPullRequestReviewContributions =
    Object.selectionForField "Int" "totalPullRequestReviewContributions" [] Decode.int


{-| How many different repositories the user committed to.
-}
totalRepositoriesWithContributedCommits : SelectionSet Int Github.Object.ContributionsCollection
totalRepositoriesWithContributedCommits =
    Object.selectionForField "Int" "totalRepositoriesWithContributedCommits" [] Decode.int


type alias TotalRepositoriesWithContributedIssuesOptionalArguments =
    { excludeFirst : OptionalArgument Bool
    , excludePopular : OptionalArgument Bool
    }


{-| How many different repositories the user opened issues in.

  - excludeFirst - Should the user's first issue ever be excluded from this count.
  - excludePopular - Should the user's most commented issue be excluded from this count.

-}
totalRepositoriesWithContributedIssues : (TotalRepositoriesWithContributedIssuesOptionalArguments -> TotalRepositoriesWithContributedIssuesOptionalArguments) -> SelectionSet Int Github.Object.ContributionsCollection
totalRepositoriesWithContributedIssues fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { excludeFirst = Absent, excludePopular = Absent }

        optionalArgs =
            [ Argument.optional "excludeFirst" filledInOptionals.excludeFirst Encode.bool, Argument.optional "excludePopular" filledInOptionals.excludePopular Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForField "Int" "totalRepositoriesWithContributedIssues" optionalArgs Decode.int


{-| How many different repositories the user left pull request reviews in.
-}
totalRepositoriesWithContributedPullRequestReviews : SelectionSet Int Github.Object.ContributionsCollection
totalRepositoriesWithContributedPullRequestReviews =
    Object.selectionForField "Int" "totalRepositoriesWithContributedPullRequestReviews" [] Decode.int


type alias TotalRepositoriesWithContributedPullRequestsOptionalArguments =
    { excludeFirst : OptionalArgument Bool
    , excludePopular : OptionalArgument Bool
    }


{-| How many different repositories the user opened pull requests in.

  - excludeFirst - Should the user's first pull request ever be excluded from this count.
  - excludePopular - Should the user's most commented pull request be excluded from this count.

-}
totalRepositoriesWithContributedPullRequests : (TotalRepositoriesWithContributedPullRequestsOptionalArguments -> TotalRepositoriesWithContributedPullRequestsOptionalArguments) -> SelectionSet Int Github.Object.ContributionsCollection
totalRepositoriesWithContributedPullRequests fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { excludeFirst = Absent, excludePopular = Absent }

        optionalArgs =
            [ Argument.optional "excludeFirst" filledInOptionals.excludeFirst Encode.bool, Argument.optional "excludePopular" filledInOptionals.excludePopular Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForField "Int" "totalRepositoriesWithContributedPullRequests" optionalArgs Decode.int


type alias TotalRepositoryContributionsOptionalArguments =
    { excludeFirst : OptionalArgument Bool }


{-| How many repositories the user created.

  - excludeFirst - Should the user's first repository ever be excluded from this count.

-}
totalRepositoryContributions : (TotalRepositoryContributionsOptionalArguments -> TotalRepositoryContributionsOptionalArguments) -> SelectionSet Int Github.Object.ContributionsCollection
totalRepositoryContributions fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { excludeFirst = Absent }

        optionalArgs =
            [ Argument.optional "excludeFirst" filledInOptionals.excludeFirst Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForField "Int" "totalRepositoryContributions" optionalArgs Decode.int


{-| The user who made the contributions in this collection.
-}
user : SelectionSet decodesTo Github.Object.User -> SelectionSet decodesTo Github.Object.ContributionsCollection
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
