-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.DeleteProjectColumnPayload exposing (clientMutationId, deletedColumnId, project)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) Github.Object.DeleteProjectColumnPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The deleted column ID.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `deletedColumnId` will change from `ID!` to `ID`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
deletedColumnId : SelectionSet Github.Scalar.Id Github.Object.DeleteProjectColumnPayload
deletedColumnId =
    Object.selectionForField "Scalar.Id" "deletedColumnId" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Id)


{-| The project the deleted column was in.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `project` will change from `Project!` to `Project`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
project : SelectionSet decodesTo Github.Object.Project -> SelectionSet decodesTo Github.Object.DeleteProjectColumnPayload
project object_ =
    Object.selectionForCompositeField "project" [] object_ identity
