-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.DeleteProjectCardPayload exposing (clientMutationId, column, deletedCardId)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) Github.Object.DeleteProjectCardPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The column the deleted card was in.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `column` will change from `ProjectColumn!` to `ProjectColumn`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
column : SelectionSet decodesTo Github.Object.ProjectColumn -> SelectionSet decodesTo Github.Object.DeleteProjectCardPayload
column object_ =
    Object.selectionForCompositeField "column" [] object_ identity


{-| The deleted card ID.

**Upcoming Change on 2019-01-01 UTC**
**Description:** Type for `deletedCardId` will change from `ID!` to `ID`.
**Reason:** In preparation for an upcoming change to the way we report mutation errors, non-nullable payload fields are becoming nullable.

-}
deletedCardId : SelectionSet Github.Scalar.Id Github.Object.DeleteProjectCardPayload
deletedCardId =
    Object.selectionForField "Scalar.Id" "deletedCardId" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Id)
