-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Interface.Contribution exposing (Fragments, fragments, isRestricted, maybeFragments, occurredAt, resourcePath, url, user)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onCreatedIssueContribution : SelectionSet decodesTo Github.Object.CreatedIssueContribution
    , onCreatedPullRequestContribution : SelectionSet decodesTo Github.Object.CreatedPullRequestContribution
    , onJoinedGitHubContribution : SelectionSet decodesTo Github.Object.JoinedGitHubContribution
    , onRestrictedContribution : SelectionSet decodesTo Github.Object.RestrictedContribution
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Github.Interface.Contribution
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "CreatedIssueContribution" selections.onCreatedIssueContribution
        , Object.buildFragment "CreatedPullRequestContribution" selections.onCreatedPullRequestContribution
        , Object.buildFragment "JoinedGitHubContribution" selections.onJoinedGitHubContribution
        , Object.buildFragment "RestrictedContribution" selections.onRestrictedContribution
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onCreatedIssueContribution = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCreatedPullRequestContribution = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onJoinedGitHubContribution = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRestrictedContribution = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| Whether this contribution is associated with a record you do not have access to. For
example, your own 'first issue' contribution may have been made on a repository you can no
longer access.
-}
isRestricted : SelectionSet Bool Github.Interface.Contribution
isRestricted =
    Object.selectionForField "Bool" "isRestricted" [] Decode.bool


{-| When this contribution was made.
-}
occurredAt : SelectionSet Github.Scalar.DateTime Github.Interface.Contribution
occurredAt =
    Object.selectionForField "Scalar.DateTime" "occurredAt" [] (Object.scalarDecoder |> Decode.map Github.Scalar.DateTime)


{-| The HTTP path for this contribution.
-}
resourcePath : SelectionSet Github.Scalar.Uri Github.Interface.Contribution
resourcePath =
    Object.selectionForField "Scalar.Uri" "resourcePath" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Uri)


{-| The HTTP URL for this contribution.
-}
url : SelectionSet Github.Scalar.Uri Github.Interface.Contribution
url =
    Object.selectionForField "Scalar.Uri" "url" [] (Object.scalarDecoder |> Decode.map Github.Scalar.Uri)


{-| The user who made this contribution.
-}
user : SelectionSet decodesTo Github.Object.User -> SelectionSet decodesTo Github.Interface.Contribution
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
