-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.AssetOrderByInput exposing (AssetOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type AssetOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Handle_ASC
    | Handle_DESC
    | FileName_ASC
    | FileName_DESC
    | Height_ASC
    | Height_DESC
    | MimeType_ASC
    | MimeType_DESC
    | Size_ASC
    | Size_DESC
    | Width_ASC
    | Width_DESC


list : List AssetOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Handle_ASC, Handle_DESC, FileName_ASC, FileName_DESC, Height_ASC, Height_DESC, MimeType_ASC, MimeType_DESC, Size_ASC, Size_DESC, Width_ASC, Width_DESC ]


decoder : Decoder AssetOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "handle_ASC" ->
                        Decode.succeed Handle_ASC

                    "handle_DESC" ->
                        Decode.succeed Handle_DESC

                    "fileName_ASC" ->
                        Decode.succeed FileName_ASC

                    "fileName_DESC" ->
                        Decode.succeed FileName_DESC

                    "height_ASC" ->
                        Decode.succeed Height_ASC

                    "height_DESC" ->
                        Decode.succeed Height_DESC

                    "mimeType_ASC" ->
                        Decode.succeed MimeType_ASC

                    "mimeType_DESC" ->
                        Decode.succeed MimeType_DESC

                    "size_ASC" ->
                        Decode.succeed Size_ASC

                    "size_DESC" ->
                        Decode.succeed Size_DESC

                    "width_ASC" ->
                        Decode.succeed Width_ASC

                    "width_DESC" ->
                        Decode.succeed Width_DESC

                    _ ->
                        Decode.fail ("Invalid AssetOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : AssetOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Handle_ASC ->
            "handle_ASC"

        Handle_DESC ->
            "handle_DESC"

        FileName_ASC ->
            "fileName_ASC"

        FileName_DESC ->
            "fileName_DESC"

        Height_ASC ->
            "height_ASC"

        Height_DESC ->
            "height_DESC"

        MimeType_ASC ->
            "mimeType_ASC"

        MimeType_DESC ->
            "mimeType_DESC"

        Size_ASC ->
            "size_ASC"

        Size_DESC ->
            "size_DESC"

        Width_ASC ->
            "width_ASC"

        Width_DESC ->
            "width_DESC"
