-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.CallToActionPlacement exposing (CallToActionPlacement(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type CallToActionPlacement
    = Header
    | Footer


list : List CallToActionPlacement
list =
    [ Header, Footer ]


decoder : Decoder CallToActionPlacement
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "Header" ->
                        Decode.succeed Header

                    "Footer" ->
                        Decode.succeed Footer

                    _ ->
                        Decode.fail ("Invalid CallToActionPlacement type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : CallToActionPlacement -> String
toString enum =
    case enum of
        Header ->
            "Header"

        Footer ->
            "Footer"
