-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.CallToActionOrderByInput exposing (CallToActionOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type CallToActionOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Placement_ASC
    | Placement_DESC
    | ActionUrl_ASC
    | ActionUrl_DESC
    | Label_ASC
    | Label_DESC


list : List CallToActionOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Placement_ASC, Placement_DESC, ActionUrl_ASC, ActionUrl_DESC, Label_ASC, Label_DESC ]


decoder : Decoder CallToActionOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "placement_ASC" ->
                        Decode.succeed Placement_ASC

                    "placement_DESC" ->
                        Decode.succeed Placement_DESC

                    "actionUrl_ASC" ->
                        Decode.succeed ActionUrl_ASC

                    "actionUrl_DESC" ->
                        Decode.succeed ActionUrl_DESC

                    "label_ASC" ->
                        Decode.succeed Label_ASC

                    "label_DESC" ->
                        Decode.succeed Label_DESC

                    _ ->
                        Decode.fail ("Invalid CallToActionOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : CallToActionOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Placement_ASC ->
            "placement_ASC"

        Placement_DESC ->
            "placement_DESC"

        ActionUrl_ASC ->
            "actionUrl_ASC"

        ActionUrl_DESC ->
            "actionUrl_DESC"

        Label_ASC ->
            "label_ASC"

        Label_DESC ->
            "label_DESC"
