-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.ExplanationBlockOrderByInput exposing (ExplanationBlockOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type ExplanationBlockOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Title_ASC
    | Title_DESC
    | Text_ASC
    | Text_DESC
    | Type_ASC
    | Type_DESC
    | Icon_ASC
    | Icon_DESC


list : List ExplanationBlockOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Title_ASC, Title_DESC, Text_ASC, Text_DESC, Type_ASC, Type_DESC, Icon_ASC, Icon_DESC ]


decoder : Decoder ExplanationBlockOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "title_ASC" ->
                        Decode.succeed Title_ASC

                    "title_DESC" ->
                        Decode.succeed Title_DESC

                    "text_ASC" ->
                        Decode.succeed Text_ASC

                    "text_DESC" ->
                        Decode.succeed Text_DESC

                    "type_ASC" ->
                        Decode.succeed Type_ASC

                    "type_DESC" ->
                        Decode.succeed Type_DESC

                    "icon_ASC" ->
                        Decode.succeed Icon_ASC

                    "icon_DESC" ->
                        Decode.succeed Icon_DESC

                    _ ->
                        Decode.fail ("Invalid ExplanationBlockOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ExplanationBlockOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Title_ASC ->
            "title_ASC"

        Title_DESC ->
            "title_DESC"

        Text_ASC ->
            "text_ASC"

        Text_DESC ->
            "text_DESC"

        Type_ASC ->
            "type_ASC"

        Type_DESC ->
            "type_DESC"

        Icon_ASC ->
            "icon_ASC"

        Icon_DESC ->
            "icon_DESC"
