-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.FaqOrderByInput exposing (FaqOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type FaqOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Question_ASC
    | Question_DESC
    | Answer_ASC
    | Answer_DESC
    | Sort_ASC
    | Sort_DESC


list : List FaqOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Question_ASC, Question_DESC, Answer_ASC, Answer_DESC, Sort_ASC, Sort_DESC ]


decoder : Decoder FaqOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "question_ASC" ->
                        Decode.succeed Question_ASC

                    "question_DESC" ->
                        Decode.succeed Question_DESC

                    "answer_ASC" ->
                        Decode.succeed Answer_ASC

                    "answer_DESC" ->
                        Decode.succeed Answer_DESC

                    "sort_ASC" ->
                        Decode.succeed Sort_ASC

                    "sort_DESC" ->
                        Decode.succeed Sort_DESC

                    _ ->
                        Decode.fail ("Invalid FaqOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : FaqOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Question_ASC ->
            "question_ASC"

        Question_DESC ->
            "question_DESC"

        Answer_ASC ->
            "answer_ASC"

        Answer_DESC ->
            "answer_DESC"

        Sort_ASC ->
            "sort_ASC"

        Sort_DESC ->
            "sort_DESC"
