-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CMS.Enum.PageOrderByInput exposing (PageOrderByInput(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type PageOrderByInput
    = Status_ASC
    | Status_DESC
    | Id_ASC
    | Id_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Title_ASC
    | Title_DESC
    | Heading_ASC
    | Heading_DESC
    | Subtitle_ASC
    | Subtitle_DESC
    | Path_ASC
    | Path_DESC


list : List PageOrderByInput
list =
    [ Status_ASC, Status_DESC, Id_ASC, Id_DESC, CreatedAt_ASC, CreatedAt_DESC, UpdatedAt_ASC, UpdatedAt_DESC, Title_ASC, Title_DESC, Heading_ASC, Heading_DESC, Subtitle_ASC, Subtitle_DESC, Path_ASC, Path_DESC ]


decoder : Decoder PageOrderByInput
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "status_ASC" ->
                        Decode.succeed Status_ASC

                    "status_DESC" ->
                        Decode.succeed Status_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "title_ASC" ->
                        Decode.succeed Title_ASC

                    "title_DESC" ->
                        Decode.succeed Title_DESC

                    "heading_ASC" ->
                        Decode.succeed Heading_ASC

                    "heading_DESC" ->
                        Decode.succeed Heading_DESC

                    "subtitle_ASC" ->
                        Decode.succeed Subtitle_ASC

                    "subtitle_DESC" ->
                        Decode.succeed Subtitle_DESC

                    "path_ASC" ->
                        Decode.succeed Path_ASC

                    "path_DESC" ->
                        Decode.succeed Path_DESC

                    _ ->
                        Decode.fail ("Invalid PageOrderByInput type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PageOrderByInput -> String
toString enum =
    case enum of
        Status_ASC ->
            "status_ASC"

        Status_DESC ->
            "status_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Title_ASC ->
            "title_ASC"

        Title_DESC ->
            "title_DESC"

        Heading_ASC ->
            "heading_ASC"

        Heading_DESC ->
            "heading_DESC"

        Subtitle_ASC ->
            "subtitle_ASC"

        Subtitle_DESC ->
            "subtitle_DESC"

        Path_ASC ->
            "path_ASC"

        Path_DESC ->
            "path_DESC"
